version: '3'
services:
  sample-node-express:
    image: "node:8"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    command: "npm start"
